@startuml

!define STATE_COLOR #87CEEB
!define ACTION_COLOR #90EE90
!define END_STATE_COLOR #FFA07A
!define VALIDATION_COLOR #FFD700

skinparam state {
    BackgroundColor STATE_COLOR
    BorderColor Black
}

skinparam stateEnd {
    BackgroundColor END_STATE_COLOR
    BorderColor Black
}

skinparam stateValidation {
    BackgroundColor VALIDATION_COLOR
    BorderColor Black
}

[*] --> Ongoing : StartGame

state Ongoing {
    [*] --> WhiteTurn: firstMove
    WhiteTurn --> BlackTurn : makeValidMove
    BlackTurn --> WhiteTurn : makeValidMove
    WhiteTurn --> WhiteTurn : makeInvalidMove
    BlackTurn --> BlackTurn : makeInvalidMove
    
    WhiteTurn --> BlackWin : isCheckmate
    WhiteTurn --> Draw : isStalemate
    BlackTurn --> Draw : isStalemate
    BlackTurn --> WhiteWin : isCheckmate
    
    WhiteTurn --> BlackWin : resign
    BlackTurn --> WhiteWin : resign
}

BlackWin --> GameOver
WhiteWin --> GameOver
Draw --> GameOver



@enduml

